### ISSUE TITLE
code

### ISSUE THREAD

**Issue by junkangfang** [p4r4mount/E-Motion#1]
If have any plan to open source？Please!

**Comment by p4r4mount** [comment]
> Do you have any plan to open source？Please!

Yes, we will gradually open source the entire project.

**Comment by junkangfang** [comment]
Thanks!!

**Comment by 2019211753** [comment]
> > Do you have any plan to open source？Please!
> 
> Yes, we will gradually open source the entire project.

Is there any update on this?
